---
abstract: 'A Simple, Stateless Template System'
author:
  - 'Sanko Robinson <sanko@cpan.org>'
build_requires:
  CPAN::Meta::Converter: '0'
  CPAN::Meta::Validator: '0'
  File::Find: '0'
  File::Spec: '0'
  JSON: '0'
  Module::Build: '0.4'
  Perl::Tidy: '0'
  Test::More: '0.94'
  perl: '5.006001'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
keywords:
  - Liquid
  - template
  - engine
  - Solution
  - stateless
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Liquid
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  File::Spec: '0'
  perl: '5.006001'
resources:
  bugtracker: http://github.com/sanko/template-liquid/issues
  changeLog: http://github.com/sanko/template-liquid/commits/
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/sanko/template-liquid.git
version: v1.0.3
